# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventsourcing_grpc/protos/application.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n+eventsourcing_grpc/protos/application.proto\x12\x12\x65ventsourcing_grpc"\x07\n\x05\x45mpty"*\n\x14NotificationsRequest\x12\x12\n\nsection_id\x18\x01'
    b' \x01(\t"%\n\x12NotificationsReply\x12\x0f\n\x07section\x18\x01'
    b' \x01(\t2\xb5\x01\n\x0b\x41pplication\x12>\n\x04Ping\x12\x19.eventsourcing_grpc.Empty\x1a\x19.eventsourcing_grpc.Empty"\x00\x12\x66\n\x10GetNotifications\x12(.eventsourcing_grpc.NotificationsRequest\x1a&.eventsourcing_grpc.NotificationsReply"\x00\x42=\n!io.eventsourcing_grpc.applicationB\x10\x41pplicationProtoP\x01\xa2\x02\x03\x45SAb\x06proto3'
)


_EMPTY = DESCRIPTOR.message_types_by_name["Empty"]
_NOTIFICATIONSREQUEST = DESCRIPTOR.message_types_by_name["NotificationsRequest"]
_NOTIFICATIONSREPLY = DESCRIPTOR.message_types_by_name["NotificationsReply"]
Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "eventsourcing_grpc.protos.application_pb2"
        # @@protoc_insertion_point(class_scope:eventsourcing_grpc.Empty)
    },
)
_sym_db.RegisterMessage(Empty)

NotificationsRequest = _reflection.GeneratedProtocolMessageType(
    "NotificationsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _NOTIFICATIONSREQUEST,
        "__module__": "eventsourcing_grpc.protos.application_pb2"
        # @@protoc_insertion_point(class_scope:eventsourcing_grpc.NotificationsRequest)
    },
)
_sym_db.RegisterMessage(NotificationsRequest)

NotificationsReply = _reflection.GeneratedProtocolMessageType(
    "NotificationsReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _NOTIFICATIONSREPLY,
        "__module__": "eventsourcing_grpc.protos.application_pb2"
        # @@protoc_insertion_point(class_scope:eventsourcing_grpc.NotificationsReply)
    },
)
_sym_db.RegisterMessage(NotificationsReply)

_APPLICATION = DESCRIPTOR.services_by_name["Application"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n!io.eventsourcing_grpc.applicationB\020ApplicationProtoP\001\242\002\003ESA"
    )
    _EMPTY._serialized_start = 67
    _EMPTY._serialized_end = 74
    _NOTIFICATIONSREQUEST._serialized_start = 76
    _NOTIFICATIONSREQUEST._serialized_end = 118
    _NOTIFICATIONSREPLY._serialized_start = 120
    _NOTIFICATIONSREPLY._serialized_end = 157
    _APPLICATION._serialized_start = 160
    _APPLICATION._serialized_end = 341
# @@protoc_insertion_point(module_scope)
