"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

class NotificationsRequest(google.protobuf.message.Message):
    """message InitRequest {
     string application_name = 1;
    }

    message FollowRequest {
     string upstream_name = 1;
     string upstream_address = 2;
    }

    message LeadRequest {
     string downstream_name = 1;
     string downstream_address = 2;
    }

    message PromptRequest {
     string upstream_name = 1;
    }
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SECTION_ID_FIELD_NUMBER: builtins.int
    section_id: typing.Text
    def __init__(
        self,
        *,
        section_id: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["section_id", b"section_id"]
    ) -> None: ...

global___NotificationsRequest = NotificationsRequest

class NotificationsReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SECTION_FIELD_NUMBER: builtins.int
    section: typing.Text
    def __init__(
        self,
        *,
        section: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["section", b"section"]
    ) -> None: ...

global___NotificationsReply = NotificationsReply
