# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventsourcing_grpc/application.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$eventsourcing_grpc/application.proto\x12\x12\x65ventsourcing_grpc"\x07\n\x05\x45mpty2M\n\x0b\x41pplication\x12>\n\x04Ping\x12\x19.eventsourcing_grpc.Empty\x1a\x19.eventsourcing_grpc.Empty"\x00\x42=\n!io.eventsourcing_grpc.applicationB\x10\x41pplicationProtoP\x01\xa2\x02\x03\x45SAb\x06proto3'
)


_EMPTY = DESCRIPTOR.message_types_by_name["Empty"]
Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "eventsourcing_grpc.application_pb2"
        # @@protoc_insertion_point(class_scope:eventsourcing_grpc.Empty)
    },
)
_sym_db.RegisterMessage(Empty)

_APPLICATION = DESCRIPTOR.services_by_name["Application"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n!io.eventsourcing_grpc.applicationB\020ApplicationProtoP\001\242\002\003ESA"
    )
    _EMPTY._serialized_start = 60
    _EMPTY._serialized_end = 67
    _APPLICATION._serialized_start = 69
    _APPLICATION._serialized_end = 146
# @@protoc_insertion_point(module_scope)
